/* ===== Tleng Quest — desafíos de construcción (verificación exhaustiva) =====
   Cada desafío define inLang(w): el juez compara tu artefacto contra TODAS las
   cadenas de Σ* hasta maxLen. tema: isla a la que pertenece. */

const count = (w, c) => [...w].filter((x) => x === c).length;

/* ---------- Constructor de AF (temas 02) ---------- */
const FA_CHALLENGES = [
  // ------ tier AFD (modo estricto: total, determinista, sin λ) ------
  { id: "afd-01", tema: "02", mode: "afd", name: "Longitud par", xp: 30, dif: 1, sigma: "01", maxLen: 8,
    desc: "Cadenas sobre {0,1} de longitud PAR (λ incluida).",
    hint: "Dos estados: 'llevo par' y 'llevo impar'. Cualquier símbolo alterna.",
    inLang: (w) => w.length % 2 === 0 },
  { id: "afd-02", tema: "02", mode: "afd", name: "Cantidad par de ceros", xp: 30, dif: 1, sigma: "01", maxLen: 8,
    desc: "Cadenas con cantidad PAR de 0s.",
    hint: "El estado recuerda la paridad de 0s vistos; los 1s no cambian nada.",
    inLang: (w) => count(w, "0") % 2 === 0 },
  { id: "afd-03", tema: "02", mode: "afd", name: "Impar de unos", xp: 30, dif: 1, sigma: "01", maxLen: 8,
    desc: "Cadenas con cantidad IMPAR de 1s.",
    hint: "Igual que paridad de ceros, pero el final es el estado 'impar'.",
    inLang: (w) => count(w, "1") % 2 === 1 },
  { id: "afd-04", tema: "02", mode: "afd", name: "Par de 0s E impar de 1s", xp: 60, dif: 2, sigma: "01", maxLen: 8,
    desc: "Cantidad par de 0s Y cantidad impar de 1s (clásico de la P2).",
    hint: "Producto de los dos autómatas: 4 estados (par/par, par/impar, impar/par, impar/impar).",
    inLang: (w) => count(w, "0") % 2 === 0 && count(w, "1") % 2 === 1 },
  { id: "afd-05", tema: "02", mode: "afd", name: "Empieza con 01", xp: 40, dif: 1, sigma: "01", maxLen: 7,
    desc: "Cadenas que COMIENZAN con 01.",
    hint: "Consumí 0 y 1; si algo falla, andá al estado TRAMPA (no final, se queda ahí). El AFD tiene que ser total.",
    inLang: (w) => w.startsWith("01") },
  { id: "afd-06", tema: "02", mode: "afd", name: "Termina en 01", xp: 50, dif: 2, sigma: "01", maxLen: 8,
    desc: "Cadenas que TERMINAN en 01.",
    hint: "El estado recuerda el sufijo útil: ¿vi un 0 suelto? ¿acabo de cerrar 01?",
    inLang: (w) => w.endsWith("01") },
  { id: "afd-07", tema: "02", mode: "afd", name: "Contiene 000", xp: 50, dif: 2, sigma: "01", maxLen: 8,
    desc: "Cadenas que contienen la subcadena 000.",
    hint: "Contá 0s consecutivos (0,1,2) y un pozo de aceptación al llegar a 3.",
    inLang: (w) => w.includes("000") },
  { id: "afd-08", tema: "02", mode: "afd", name: "NO contiene 000", xp: 50, dif: 2, sigma: "01", maxLen: 8,
    desc: "Cadenas que NO contienen 000. (Complemento: invertí finales del anterior.)",
    hint: "Mismo autómata que 'contiene 000' pero con los finales invertidos — solo vale en AFD completo.",
    inLang: (w) => !w.includes("000") },
  { id: "afd-09", tema: "02", mode: "afd", name: "Múltiplo de 3 en binario", xp: 70, dif: 3, sigma: "01", maxLen: 8,
    desc: "Cadenas no vacías que, leídas como número binario, son ≡ 0 (mod 3). Ej: 110 (6) ✓, 101 (5) ✗.",
    hint: "Horner: el estado es el resto mod 3; con el bit b pasás a (2r+b) mod 3. Ojo: λ NO está en el lenguaje (usá un estado inicial aparte).",
    inLang: (w) => w.length > 0 && [...w].reduce((r, b) => (2 * r + +b) % 3, 0) === 0 },
  { id: "afd-10", tema: "02", mode: "afd", name: "Exactamente un 1", xp: 40, dif: 1, sigma: "01", maxLen: 8,
    desc: "Cadenas con EXACTAMENTE un 1.",
    hint: "Tres estados: cero unos, un uno (final), más de uno (trampa).",
    inLang: (w) => count(w, "1") === 1 },
  { id: "afd-11", tema: "02", mode: "afd", name: "Sin dos a seguidas", xp: 50, dif: 2, sigma: "ab", maxLen: 8,
    desc: "Cadenas sobre {a,b} SIN dos a consecutivas.",
    hint: "Recordá si lo último fue una a; otra a te manda a la trampa.",
    inLang: (w) => !w.includes("aa") },
  { id: "afd-12", tema: "02", mode: "afd", name: "Resto 2 módulo 5", xp: 90, dif: 3, sigma: "01", maxLen: 7,
    desc: "Cadenas no vacías que en binario son ≡ 2 (mod 5). El mod 5 de la P2, nivel final.",
    hint: "Cinco estados r0..r4 + inicial aparte; δ(r,b) = (2r+b) mod 5; final: r2.",
    inLang: (w) => w.length > 0 && [...w].reduce((r, b) => (2 * r + +b) % 5, 0) === 2 },
  // ------ tier AFND (vale no determinismo y λ) ------
  { id: "afnd-01", tema: "02", mode: "afnd", name: "Termina en 010", xp: 50, dif: 1, sigma: "01", maxLen: 8,
    desc: "Cadenas que terminan en 010. En AFND es natural: adiviná dónde empieza el sufijo.",
    hint: "Un loop 0,1 en el inicial y una cadenita 0→1→0 al final. El no determinismo adivina.",
    inLang: (w) => w.endsWith("010") },
  { id: "afnd-02", tema: "02", mode: "afnd", name: "Contiene 101", xp: 50, dif: 1, sigma: "01", maxLen: 8,
    desc: "Cadenas que contienen 101.",
    hint: "Loop al principio, consumí 101, loop al final.",
    inLang: (w) => w.includes("101") },
  { id: "afnd-03", tema: "02", mode: "afnd", name: "Anteúltimo símbolo es 1", xp: 60, dif: 2, sigma: "01", maxLen: 8,
    desc: "Cadenas donde el ANTEÚLTIMO símbolo es 1 (clásico: el AFD equivalente necesita 4 estados, el AFND 3).",
    hint: "Adiviná que estás a 2 del final: q0 --loop--> q0 --1--> q1 --0,1--> q2 final.",
    inLang: (w) => w.length >= 2 && w[w.length - 2] === "1" },
  { id: "afnd-04", tema: "02", mode: "afnd", name: "a* b*", xp: 50, dif: 1, sigma: "ab", maxLen: 8,
    desc: "Todas las a antes que todas las b (λ, aa, abb ✓ · aba ✗). Usá una transición λ.",
    hint: "Dos estados con loops (a y b) unidos por una λ. Los dos finales... o solo el segundo.",
    inLang: (w) => /^a*b*$/.test(w) },
  { id: "afnd-05", tema: "02", mode: "afnd", name: "Empieza con ab O termina con ba", xp: 70, dif: 2, sigma: "ab", maxLen: 7,
    desc: "Unión de dos lenguajes: la construcción de unión con λ desde un inicial nuevo.",
    hint: "Estado inicial nuevo con dos λ: una rama chequea el prefijo ab, la otra adivina el sufijo ba.",
    inLang: (w) => w.startsWith("ab") || w.endsWith("ba") },
  { id: "afnd-06", tema: "02", mode: "afnd", name: "Contiene ab Y contiene ba", xp: 80, dif: 3, sigma: "ab", maxLen: 7,
    desc: "Las dos subcadenas tienen que aparecer (en cualquier orden).",
    hint: "Pensalo como AFD de producto… o notá que equivale a 'contiene ab seguido de ba o ba seguido de ab' con solapamiento (aba, bab cuentan).",
    inLang: (w) => w.includes("ab") && w.includes("ba") },
];

/* ---------- Constructor de AP (tema 07) ---------- */
const PDA_CHALLENGES = [
  { id: "pda-01", tema: "07", name: "aⁿbⁿ", xp: 60, dif: 1, sigma: "ab", maxLen: 8, accept: "any",
    desc: "L = { aⁿbⁿ : n ≥ 0 }. EL clásico. Apilá las a, desapilá con las b.",
    hint: "δ(q0,a,Z)=(q0,AZ), δ(q0,a,A)=(q0,AA), λ para pasar a desapilar, δ(q1,b,A)=(q1,λ), y aceptá con Z limpio.",
    inLang: (w) => /^a*b*$/.test(w) && count(w, "a") === count(w, "b") },
  { id: "pda-02", tema: "07", name: "aⁿbᵐ con m > n", xp: 70, dif: 2, sigma: "ab", maxLen: 8, accept: "any",
    desc: "Más b que a (y todas las a primero). Ojo el caso n=0: 'b' ∈ L.",
    hint: "Como aⁿbⁿ pero después de emparejar, tienen que sobrar b: consumí al menos una b extra con el fondo de pila a la vista.",
    inLang: (w) => /^a*b*$/.test(w) && count(w, "b") > count(w, "a") },
  { id: "pda-03", tema: "07", name: "Igual cantidad de a y b", xp: 80, dif: 2, sigma: "ab", maxLen: 8, accept: "any",
    desc: "|w|ₐ = |w|ᵦ, mezcladas como sea (abba, ab, bbaa ✓).",
    hint: "Invariante 'un solo signo en la pila': apilás el símbolo en exceso y cancelás con el contrario.",
    inLang: (w) => count(w, "a") === count(w, "b") },
  { id: "pda-04", tema: "07", name: "w # wʳ", xp: 80, dif: 2, sigma: "ab#", maxLen: 7, accept: "any",
    desc: "Espejo con marcador: aba#aba ✓ (w=aba, wʳ=aba... ojo, ¡el reverso!). ab#ba ✓.",
    hint: "Apilá todo hasta el #; después de # desapilá si coincide. La pila te devuelve w AL REVÉS: eso ES wʳ.",
    inLang: (w) => { const i = w.indexOf("#"); if (i < 0 || w.lastIndexOf("#") !== i) return false;
      const a = w.slice(0, i), b = w.slice(i + 1); return b === [...a].reverse().join(""); } },
  { id: "pda-05", tema: "07", name: "Paréntesis balanceados", xp: 70, dif: 2, sigma: "()", maxLen: 8, accept: "any",
    desc: "El lenguaje de Dyck: (), (()) (), ✓ · )(, (() ✗. λ ∈ L.",
    hint: "Apilá con '(' y desapilá con ')'. Rechazo automático: ')' con pila sin paréntesis.",
    inLang: (w) => { let d = 0; for (const c of w) { d += c === "(" ? 1 : -1; if (d < 0) return false; } return d === 0; } },
  { id: "pda-06", tema: "07", name: "aⁿb²ⁿ", xp: 90, dif: 3, sigma: "ab", maxLen: 8, accept: "any",
    desc: "El doble de b que de a, todas las a primero: ab b, aabbbb ✓.",
    hint: "Por cada a apilá DOS símbolos (push AA); cada b desapila uno.",
    inLang: (w) => /^a*b*$/.test(w) && count(w, "b") === 2 * count(w, "a") },
];

/* ---------- ER Golf (tema 04) ---------- */
const ER_CHALLENGES = [
  { id: "er-01", tema: "04", name: "Termina en 01", xp: 40, dif: 1, sigma: "01", maxLen: 8, par: 7,
    desc: "Cadenas que terminan en 01.", hint: "Cualquier cosa y después 01.",
    inLang: (w) => w.endsWith("01") },
  { id: "er-02", tema: "04", name: "a* b*", xp: 30, dif: 1, sigma: "ab", maxLen: 8, par: 4,
    desc: "Todas las a antes que todas las b.", hint: "Es literal.",
    inLang: (w) => /^a*b*$/.test(w) },
  { id: "er-03", tema: "04", name: "Contiene 000", xp: 40, dif: 1, sigma: "01", maxLen: 8, par: 12,
    desc: "Cadenas que contienen 000.", hint: "Sandwich: basura, 000, basura.",
    inLang: (w) => w.includes("000") },
  { id: "er-04", tema: "04", name: "Cantidad par de ceros", xp: 60, dif: 2, sigma: "01", maxLen: 8, par: 12,
    desc: "Cantidad PAR de 0s (λ cuenta).", hint: "Bloques que consumen los 0s de a dos: 1*(01*01*)*.",
    inLang: (w) => count(w, "0") % 2 === 0 },
  { id: "er-05", tema: "04", name: "Sin dos a seguidas", xp: 60, dif: 2, sigma: "ab", maxLen: 8, par: 12,
    desc: "Sin aa como subcadena.", hint: "Cada a va seguida de b… salvo quizás la última: (b|ab)*(a|λ).",
    inLang: (w) => !w.includes("aa") },
  { id: "er-06", tema: "04", name: "Longitud múltiplo de 3", xp: 50, dif: 2, sigma: "01", maxLen: 9, par: 18,
    desc: "|w| ≡ 0 (mod 3), λ incluida.", hint: "De a tres símbolos cualesquiera.",
    inLang: (w) => w.length % 3 === 0 },
  { id: "er-07", tema: "04", name: "Exactamente dos b", xp: 50, dif: 2, sigma: "ab", maxLen: 8, par: 11,
    desc: "Exactamente dos b (las a, libres).", hint: "a* b a* b a*.",
    inLang: (w) => count(w, "b") === 2 },
  { id: "er-08", tema: "04", name: "Empieza y termina igual", xp: 80, dif: 3, sigma: "01", maxLen: 8, par: 21,
    desc: "No vacías que empiezan y terminan con el MISMO símbolo (0, 1, 010 ✗… ojo: '0' sola ✓).",
    hint: "Cuatro casos: 0, 1, 0…0, 1…1. Unión.",
    inLang: (w) => w.length >= 1 && w[0] === w[w.length - 1] },
];

/* ---------- Gramática Lab (tema 08) ---------- */
const CFG_CHALLENGES = [
  { id: "cfg-01", tema: "08", name: "aⁿbⁿ", xp: 50, dif: 1, sigma: "ab", maxLen: 8,
    desc: "L = { aⁿbⁿ : n ≥ 0 }.", hint: "S -> a S b | λ. LA plantilla.",
    inLang: (w) => /^a*b*$/.test(w) && count(w, "a") === count(w, "b") },
  { id: "cfg-02", tema: "08", name: "Palíndromos pares (w wʳ)", xp: 60, dif: 1, sigma: "ab", maxLen: 8,
    desc: "Cadenas de la forma w·wʳ: abba, aa ✓ · aba ✗ (impar).",
    hint: "Generá de afuera hacia adentro: S -> aSa | bSb | λ.",
    inLang: (w) => w.length % 2 === 0 && w === [...w].reverse().join("") },
  { id: "cfg-03", tema: "08", name: "Todos los palíndromos", xp: 60, dif: 2, sigma: "ab", maxLen: 7,
    desc: "w = wʳ (pares e impares, λ incluida).",
    hint: "Como el anterior pero con centros: | a | b.",
    inLang: (w) => w === [...w].reverse().join("") },
  { id: "cfg-04", tema: "08", name: "Igual cantidad de a y b", xp: 90, dif: 3, sigma: "ab", maxLen: 8,
    desc: "|w|ₐ = |w|ᵦ mezcladas (abba, ba ✓).",
    hint: "El balanceo clásico: S -> a S b S | b S a S | λ.",
    inLang: (w) => count(w, "a") === count(w, "b") },
  { id: "cfg-05", tema: "08", name: "aⁿbᵐ con n < m", xp: 70, dif: 2, sigma: "ab", maxLen: 8,
    desc: "Más b que a, todas las a primero.",
    hint: "El núcleo aⁿbⁿ más un excedente OBLIGATORIO de b: S -> N B, N -> aNb | λ, B -> bB | b.",
    inLang: (w) => /^a*b*$/.test(w) && count(w, "a") < count(w, "b") },
  { id: "cfg-06", tema: "08", name: "Dyck (paréntesis)", xp: 70, dif: 2, sigma: "()", maxLen: 8,
    desc: "Paréntesis balanceados. Usá ( y ) como terminales.",
    hint: "La versión NO ambigua: S -> ( S ) S | λ.",
    inLang: (w) => { let d = 0; for (const c of w) { d += c === "(" ? 1 : -1; if (d < 0) return false; } return d === 0; } },
  { id: "cfg-07", tema: "08", name: "aⁱbʲ con i≠j", xp: 90, dif: 3, sigma: "ab", maxLen: 8,
    desc: "Forma a*b* pero con CANTIDADES DISTINTAS de a y b. El '≠' del final.",
    hint: "'≠' = unión de '<' y '>': dos ramas, cada una con su excedente obligatorio.",
    inLang: (w) => /^a*b*$/.test(w) && count(w, "a") !== count(w, "b") },
  { id: "cfg-08", tema: "08", name: "|w|ₐ = 2·|w|ᵦ", xp: 100, dif: 3, sigma: "ab", maxLen: 8,
    desc: "El doble de a que de b, mezcladas como sea (aab, abaaba ✓).",
    hint: "Cada b 'vale' dos a: S -> S a S a S b S | S a S b S a S | S b S a S a S | λ (¡y simplificá!).",
    inLang: (w) => count(w, "a") === 2 * count(w, "b") },
];

const ALL_CHALLENGES = { fa: FA_CHALLENGES, pda: PDA_CHALLENGES, er: ER_CHALLENGES, cfg: CFG_CHALLENGES };
